spring.application.name=LibraryInfoDisplay
logging.level.root=INFO
logging.level.com.assignment1.LibraryInfoDisplay=DEBUG
library.csv.path=data/books_catalog.csv
library.csv.header=id,bookName,authorName,category,publisher,price,quantity,publishedYear,isbn,language